# Generated by Django 3.2.3 on 2021-06-02 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.BooleanField(choices=[('DONE', 'Done'), ('NOT DONE', 'Not done')], default='Not done'),
        ),
    ]
